<a href="https://colab.research.google.com/github/jjjuurang/CLIP/blob/main/TPAMI_AMT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
true  = True
false = False

In [2]:
A = [{"1":{"audio":true,"tedi":false,"text":false},"10":{"explosion":false,"fire":false,"raining":false,"water":true},"11":{"explosion":false,"fire":false,"raining":false,"water":true},"12":{"explosion":false,"fire":false,"raining":true,"water":false},"13":{"explosion":false,"fire":false,"raining":true,"water":false},"14":{"explosion":false,"fire":true,"raining":false,"water":false},"15":{"explosion":false,"fire":true,"raining":false,"water":false},"16":{"explosion":false,"fire":false,"raining":false,"water":true},"17":{"explosion":false,"fire":true,"raining":false,"water":false},"18":{"explosion":false,"fire":false,"raining":false,"water":true},"19":{"explosion":false,"fire":false,"raining":false,"water":true},"2":{"audio":true,"tedi":false,"text":false},"20":{"explosion":false,"fire":false,"raining":false,"water":true},"21":{"explosion":false,"fire":false,"raining":false,"water":true},"22":{"explosion":false,"fire":false,"raining":false,"water":true},"23":{"explosion":false,"fire":false,"raining":false,"water":true},"24":{"explosion":true,"fire":false,"raining":false,"water":false},"25":{"explosion":false,"fire":false,"raining":false,"water":true},"26":{"explosion":false,"fire":true,"raining":false,"water":false},"27":{"explosion":true,"fire":false,"raining":false,"water":false},"28":{"explosion":true,"fire":false,"raining":false,"water":false},"29":{"explosion":false,"fire":false,"raining":false,"water":true},"3":{"audio":true,"tedi":false,"text":false},"30":{"explosion":false,"fire":false,"raining":false,"water":true},"31":{"explosion":false,"fire":false,"raining":false,"water":true},"32":{"explosion":false,"fire":false,"raining":true,"water":false},"33":{"explosion":false,"fire":false,"raining":true,"water":false},"34":{"explosion":false,"fire":false,"raining":false,"water":true},"35":{"explosion":false,"fire":false,"raining":true,"water":false},"4":{"audio":false,"tedi":false,"text":true},"5":{"audio":true,"tedi":false,"text":false},"6":{"explosion":true,"fire":false,"raining":false,"water":false},"7":{"explosion":false,"fire":true,"raining":false,"water":false},"8":{"explosion":false,"fire":true,"raining":false,"water":false},"9":{"explosion":false,"fire":false,"raining":false,"water":true}}]

In [4]:
len(A)

1

In [5]:
A[0]

{'1': {'audio': True, 'tedi': False, 'text': False},
 '10': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '11': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '12': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
 '13': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
 '14': {'explosion': False, 'fire': True, 'raining': False, 'water': False},
 '15': {'explosion': False, 'fire': True, 'raining': False, 'water': False},
 '16': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '17': {'explosion': False, 'fire': True, 'raining': False, 'water': False},
 '18': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '19': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '2': {'audio': True, 'tedi': False, 'text': False},
 '20': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '21': {'explosion': False, 'fire': False, 'rai

In [11]:
B = sorted(A[0].items())

In [12]:
B

[('1', {'audio': True, 'tedi': False, 'text': False}),
 ('10', {'explosion': False, 'fire': False, 'raining': False, 'water': True}),
 ('11', {'explosion': False, 'fire': False, 'raining': False, 'water': True}),
 ('12', {'explosion': False, 'fire': False, 'raining': True, 'water': False}),
 ('13', {'explosion': False, 'fire': False, 'raining': True, 'water': False}),
 ('14', {'explosion': False, 'fire': True, 'raining': False, 'water': False}),
 ('15', {'explosion': False, 'fire': True, 'raining': False, 'water': False}),
 ('16', {'explosion': False, 'fire': False, 'raining': False, 'water': True}),
 ('17', {'explosion': False, 'fire': True, 'raining': False, 'water': False}),
 ('18', {'explosion': False, 'fire': False, 'raining': False, 'water': True}),
 ('19', {'explosion': False, 'fire': False, 'raining': False, 'water': True}),
 ('2', {'audio': True, 'tedi': False, 'text': False}),
 ('20', {'explosion': False, 'fire': False, 'raining': False, 'water': True}),
 ('21', {'explosion':

In [13]:
A2 = [{"1":{"audio":true,"tedi":false,"text":false},"10":{"explosion":false,"fire":false,"raining":false,"water":true},"11":{"explosion":false,"fire":false,"raining":true,"water":false},"12":{"explosion":false,"fire":false,"raining":true,"water":false},"13":{"explosion":false,"fire":false,"raining":true,"water":false},"14":{"explosion":false,"fire":true,"raining":false,"water":false},"15":{"explosion":true,"fire":false,"raining":false,"water":false},"16":{"explosion":false,"fire":false,"raining":false,"water":true},"17":{"explosion":false,"fire":false,"raining":true,"water":false},"18":{"explosion":false,"fire":false,"raining":false,"water":true},"19":{"explosion":false,"fire":false,"raining":false,"water":true},"2":{"audio":true,"tedi":false,"text":false},"20":{"explosion":false,"fire":false,"raining":false,"water":true},"21":{"explosion":false,"fire":false,"raining":false,"water":true},"22":{"explosion":false,"fire":false,"raining":true,"water":false},"23":{"explosion":false,"fire":false,"raining":false,"water":true},"24":{"explosion":false,"fire":false,"raining":false,"water":true},"25":{"explosion":false,"fire":false,"raining":false,"water":true},"26":{"explosion":true,"fire":false,"raining":false,"water":false},"27":{"explosion":true,"fire":false,"raining":false,"water":false},"28":{"explosion":true,"fire":false,"raining":false,"water":false},"29":{"explosion":false,"fire":false,"raining":false,"water":true},"3":{"audio":true,"tedi":false,"text":false},"30":{"explosion":false,"fire":false,"raining":false,"water":true},"31":{"explosion":false,"fire":false,"raining":false,"water":true},"32":{"explosion":false,"fire":false,"raining":true,"water":false},"33":{"explosion":false,"fire":false,"raining":true,"water":false},"34":{"explosion":false,"fire":false,"raining":true,"water":false},"35":{"explosion":false,"fire":false,"raining":false,"water":true},"4":{"audio":true,"tedi":false,"text":false},"5":{"audio":false,"tedi":true,"text":false},"6":{"explosion":true,"fire":false,"raining":false,"water":false},"7":{"explosion":true,"fire":false,"raining":false,"water":false},"8":{"explosion":true,"fire":false,"raining":false,"water":false},"9":{"explosion":false,"fire":false,"raining":false,"water":true}}]

In [14]:
A2[0]

{'1': {'audio': True, 'tedi': False, 'text': False},
 '10': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '11': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
 '12': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
 '13': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
 '14': {'explosion': False, 'fire': True, 'raining': False, 'water': False},
 '15': {'explosion': True, 'fire': False, 'raining': False, 'water': False},
 '16': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '17': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
 '18': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '19': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '2': {'audio': True, 'tedi': False, 'text': False},
 '20': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
 '21': {'explosion': False, 'fire': False, 'rai

In [15]:
keyList = A[0].keys()

In [16]:
keyList

dict_keys(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '4', '5', '6', '7', '8', '9'])

In [17]:
for item in keyList:
  print(A[0][item])

{'audio': True, 'tedi': False, 'text': False}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'explosion': False, 'fire': False, 'raining': True, 'water': False}
{'explosion': False, 'fire': False, 'raining': True, 'water': False}
{'explosion': False, 'fire': True, 'raining': False, 'water': False}
{'explosion': False, 'fire': True, 'raining': False, 'water': False}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'explosion': False, 'fire': True, 'raining': False, 'water': False}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'audio': True, 'tedi': False, 'text': False}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'explosion': False, 'fire': False, 'raining': False, 'water': True}
{'explosion

In [22]:
A[0]['1']

{'audio': True, 'tedi': False, 'text': False}

In [24]:
inkeyList = A[0]['1'].keys()

In [25]:
inkeyList

dict_keys(['audio', 'tedi', 'text'])

In [26]:
for initem in inkeyList:
  print(A[0]['1'][initem])

True
False
False


In [38]:
import pandas as pd
csv = pd.read_csv("/content/TPAMIE2.csv",names=["result"])

In [82]:
import pandas as pd
csv = pd.read_csv("/content/TPAMIC.csv",names=["result"])

In [83]:
print(len(csv['result'].values.tolist()))

103


In [84]:
R = csv['result'].values.tolist()

In [41]:
R

['[{"1":{"audio":true,"tedi":false,"text":false},"10":{"explosion":false,"fire":false,"raining":false,"water":true},"11":{"explosion":false,"fire":false,"raining":false,"water":true},"12":{"explosion":false,"fire":false,"raining":true,"water":false},"13":{"explosion":false,"fire":false,"raining":true,"water":false},"14":{"explosion":false,"fire":true,"raining":false,"water":false},"15":{"explosion":false,"fire":true,"raining":false,"water":false},"16":{"explosion":false,"fire":false,"raining":false,"water":true},"17":{"explosion":false,"fire":true,"raining":false,"water":false},"18":{"explosion":false,"fire":false,"raining":false,"water":true},"19":{"explosion":false,"fire":false,"raining":false,"water":true},"2":{"audio":true,"tedi":false,"text":false},"20":{"explosion":false,"fire":false,"raining":false,"water":true},"21":{"explosion":false,"fire":false,"raining":false,"water":true},"22":{"explosion":false,"fire":false,"raining":false,"water":true},"23":{"explosion":false,"fire":fals

In [85]:
print(len(R))

103


In [48]:
print(R[0])

[{"1":{"audio":true,"tedi":false,"text":false},"10":{"explosion":false,"fire":false,"raining":false,"water":true},"11":{"explosion":false,"fire":false,"raining":false,"water":true},"12":{"explosion":false,"fire":false,"raining":true,"water":false},"13":{"explosion":false,"fire":false,"raining":true,"water":false},"14":{"explosion":false,"fire":true,"raining":false,"water":false},"15":{"explosion":false,"fire":true,"raining":false,"water":false},"16":{"explosion":false,"fire":false,"raining":false,"water":true},"17":{"explosion":false,"fire":true,"raining":false,"water":false},"18":{"explosion":false,"fire":false,"raining":false,"water":true},"19":{"explosion":false,"fire":false,"raining":false,"water":true},"2":{"audio":true,"tedi":false,"text":false},"20":{"explosion":false,"fire":false,"raining":false,"water":true},"21":{"explosion":false,"fire":false,"raining":false,"water":true},"22":{"explosion":false,"fire":false,"raining":false,"water":true},"23":{"explosion":false,"fire":false,

In [55]:
eval(R[0])

[{'1': {'audio': True, 'tedi': False, 'text': False},
  '10': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
  '11': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
  '12': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
  '13': {'explosion': False, 'fire': False, 'raining': True, 'water': False},
  '14': {'explosion': False, 'fire': True, 'raining': False, 'water': False},
  '15': {'explosion': False, 'fire': True, 'raining': False, 'water': False},
  '16': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
  '17': {'explosion': False, 'fire': True, 'raining': False, 'water': False},
  '18': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
  '19': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
  '2': {'audio': True, 'tedi': False, 'text': False},
  '20': {'explosion': False, 'fire': False, 'raining': False, 'water': True},
  '21': {'explosion': False, 'fire

In [56]:
print(type(eval(R[0])))

<class 'list'>


In [59]:
len(eval(R[0]))

1

In [86]:
print(eval(R[0])[0])

{'1': {'audio': True, 'tedi': False, 'text': False}, '10': {'explosion': False, 'fire': False, 'raining': False, 'water': True}, '11': {'explosion': False, 'fire': False, 'raining': False, 'water': True}, '12': {'explosion': False, 'fire': False, 'raining': True, 'water': False}, '13': {'explosion': False, 'fire': False, 'raining': True, 'water': False}, '14': {'explosion': False, 'fire': True, 'raining': False, 'water': False}, '15': {'explosion': False, 'fire': True, 'raining': False, 'water': False}, '16': {'explosion': False, 'fire': False, 'raining': False, 'water': True}, '17': {'explosion': False, 'fire': True, 'raining': False, 'water': False}, '18': {'explosion': False, 'fire': False, 'raining': False, 'water': True}, '19': {'explosion': False, 'fire': False, 'raining': False, 'water': True}, '2': {'audio': True, 'tedi': False, 'text': False}, '20': {'explosion': False, 'fire': False, 'raining': False, 'water': True}, '21': {'explosion': False, 'fire': False, 'raining': False,

In [87]:
eval(R[0])[0]["1"]

{'audio': True, 'tedi': False, 'text': False}

In [88]:
eval(R[0])[0]["1"]["audio"]

True

In [71]:
S1 = ["1", "2", "3", "4", "5"]

In [72]:
for i in range(len(R)):
  if eval(R[0])[0]["1"]["audio"] == True:
    Q1to5[0][0] += 1


In [76]:
Best = ["audio", "tedi", "text"]
Sound = ["explosion", "fire", "raining", "water"]

In [89]:
print(Q1to5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [90]:
for i in range(len(R)):
  for j in range(30):
    for k in Best:
      if eval(R[i])[0][str(j+1)][k] == True:
        Q1to5[j][Best.index(k)] += 1

In [91]:
print(Q1to5)

[[99.  1.  3.]
 [95.  4.  4.]
 [97.  3.  3.]
 [84. 10.  9.]
 [58. 34. 11.]]


In [96]:
print(Q6)

[[ 26.  64.   2.  11.]
 [ 45.  57.   0.   1.]
 [ 46.  57.   0.   0.]
 [ 17.   0.   3.  83.]
 [ 28.   1.   4.  70.]
 [  4.   6.  41.  52.]
 [  4.   3.  46.  50.]
 [ 11.   2.  72.  18.]
 [ 15.  83.   3.   2.]
 [ 10.  89.   3.   1.]
 [ 19.  13.  37.  34.]
 [ 10.  40.  46.   7.]
 [ 29.   1.   8.  65.]
 [ 37.  14.  23.  29.]
 [ 15.  12.  31.  45.]
 [ 27.   5.  14.  57.]
 [  4.   2.  33.  64.]
 [  0.   1.   2. 100.]
 [ 35.   3.  12.  53.]
 [  3.   2.   0.  98.]
 [ 47.  51.   1.   4.]
 [ 39.  17.  17.  30.]
 [ 55.  47.   0.   1.]
 [  8.   1.   2.  92.]
 [  0.   0.   1. 102.]
 [  1.   1.   1. 100.]
 [ 11.   3.  64.  25.]
 [  4.   2.  84.  13.]
 [ 23.   3.  26.  51.]
 [ 20.  13.  58.  12.]]


In [95]:
for i in range(len(R)):
  for j in range(6,36):
    for k in Sound:
      if eval(R[i])[0][str(j)][k] == True:
        Q6[j-6][Sound.index(k)] += 1

In [68]:
import json
J = eval(R[0])[0]
JO = json.loads(J)
print(JO['1'])

TypeError: ignored

In [64]:
eval(eval(R[0])[0])

TypeError: ignored

In [ ]:
Rlist = R[0].split(",")

In [49]:
print(len(R[0]))

2234


In [52]:
print(R[0][2])

"


In [80]:
import numpy as np
Q1to5 = np.zeros((5,3))

In [92]:
import numpy as np
Q6 = np.zeros((30,4))

In [ ]:
for i in range(len(R)):
  R[i] 

In [53]:
import json
with open("/content/csvjson.json","r") as f:
  jd = json.load(f)
print(json.dumps(jd))

[{"[{\"1\":{\"audio\":true,\"tedi\":false,\"text\":false},\"10\":{\"explosion\":false,\"fire\":false,\"raining\":false,\"water\":true},\"11\":{\"explosion\":false,\"fire\":false,\"raining\":false,\"water\":true},\"12\":{\"explosion\":false,\"fire\":false,\"raining\":true,\"water\":false},\"13\":{\"explosion\":false,\"fire\":false,\"raining\":true,\"water\":false},\"14\":{\"explosion\":false,\"fire\":true,\"raining\":false,\"water\":false},\"15\":{\"explosion\":false,\"fire\":true,\"raining\":false,\"water\":false},\"16\":{\"explosion\":false,\"fire\":false,\"raining\":false,\"water\":true},\"17\":{\"explosion\":false,\"fire\":true,\"raining\":false,\"water\":false},\"18\":{\"explosion\":false,\"fire\":false,\"raining\":false,\"water\":true},\"19\":{\"explosion\":false,\"fire\":false,\"raining\":false,\"water\":true},\"2\":{\"audio\":true,\"tedi\":false,\"text\":false},\"20\":{\"explosion\":false,\"fire\":false,\"raining\":false,\"water\":true},\"21\":{\"explosion\":false,\"fire\":false

In [54]:
len(json.dumps(jd))

5120