<a href="https://colab.research.google.com/github/jjjuurang/CLIP/blob/main/TPAMI631.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [184]:
true  = True
false = False

In [185]:
import pandas as pd
csv = pd.read_csv("/content/TPAMI603010.csv",names=["result"])

In [186]:
R = csv['result'].values.tolist()

In [187]:
eval(R[0])[0]["1"]

{'audio': True, 'tedi': False, 'text': False}

In [188]:
eval(R[0])[0]["1"]["audio"]

True

In [189]:
Best = ["audio", "tedi", "text"]
Sound = ["explosion", "fire", "raining", "water"]

In [190]:
import numpy as np
S1 = np.zeros((203,1))
S2 = np.zeros((203,1))
S3 = np.zeros((203,1))

In [191]:
for i in range(len(R)):
  s=0
  for j in range(5):
    if eval(R[i])[0][str(j+1)]["audio"] == True:
      s+=1
  S1[i][0]=s

In [192]:
for i in range(len(R)):
  s=0
  for j in range(5):
    if eval(R[i])[0][str(j+1)]["tedi"] == True:
      s+=1
  S2[i][0]=s

In [193]:
for i in range(len(R)):
  s=0
  for j in range(5):
    if eval(R[i])[0][str(j+1)]["text"] == True:
      s+=1
  S3[i][0]=s

In [248]:
print(U1)
print(U2)

[0. 1. 2. 3. 4. 5.]
[0. 1. 2. 3. 4.]


In [247]:
print(len(U1))

6


In [194]:
U1=np.unique(S1)
U2=np.unique(S2)
U3=np.unique(S3)

In [206]:
P1=[]
for i in range(len(U1)):
  line = []
  P1.append(line)

In [207]:
for i in range(203):
  for j in U1:
    if S1[i][0]==j:
      P1[U1.tolist().index(j)].append(i)

In [208]:
print(P1)

[[94, 129, 137, 142, 159, 167, 182], [8, 63, 73, 120, 138, 198], [100, 132, 143, 146, 157, 161, 174, 181, 189, 194], [2, 10, 28, 34, 58, 60, 62, 67, 75, 76, 90, 121, 126, 133, 147, 151, 166, 170, 173, 183, 196, 197], [0, 1, 6, 12, 13, 16, 18, 19, 21, 26, 27, 31, 33, 36, 39, 40, 42, 44, 48, 49, 53, 54, 59, 61, 64, 65, 66, 71, 72, 77, 78, 79, 80, 84, 86, 89, 93, 97, 99, 101, 104, 105, 106, 109, 112, 114, 115, 116, 122, 123, 128, 130, 131, 135, 139, 141, 144, 145, 148, 149, 150, 152, 153, 154, 155, 156, 162, 168, 175, 178, 184, 187, 190, 191, 192, 193, 195, 199, 200, 202], [3, 4, 5, 7, 9, 11, 14, 15, 17, 20, 22, 23, 24, 25, 29, 30, 32, 35, 37, 38, 41, 43, 45, 46, 47, 50, 51, 52, 55, 56, 57, 68, 69, 70, 74, 81, 82, 83, 85, 87, 88, 91, 92, 95, 96, 98, 102, 103, 107, 108, 110, 111, 113, 117, 118, 119, 124, 125, 127, 134, 136, 140, 158, 160, 163, 164, 165, 169, 171, 172, 176, 177, 179, 180, 185, 186, 188, 201]]


In [214]:
P2=[]
for i in range(len(U2)):
  line = []
  P2.append(line)

In [215]:
for i in range(203):
  for j in U2:
    if S2[i][0]==j:
      P2[U2.tolist().index(j)].append(i)

In [216]:
print(P2)

[[0, 3, 4, 5, 7, 9, 10, 11, 14, 15, 16, 17, 20, 22, 23, 24, 25, 26, 29, 30, 32, 34, 35, 37, 38, 40, 41, 43, 45, 46, 47, 50, 51, 52, 53, 55, 56, 57, 61, 62, 68, 69, 70, 74, 75, 77, 79, 81, 82, 83, 84, 85, 87, 88, 89, 91, 92, 95, 96, 97, 98, 102, 103, 105, 107, 108, 110, 111, 112, 113, 114, 117, 118, 119, 124, 125, 127, 130, 134, 136, 140, 142, 144, 147, 158, 160, 163, 164, 165, 169, 170, 171, 172, 175, 176, 177, 179, 180, 185, 186, 188, 191, 200, 201, 202], [1, 2, 6, 12, 13, 18, 19, 21, 27, 31, 33, 36, 39, 42, 44, 48, 49, 54, 59, 60, 64, 65, 66, 71, 72, 76, 78, 80, 86, 90, 93, 99, 101, 104, 106, 109, 115, 116, 121, 122, 123, 126, 128, 131, 132, 133, 135, 139, 141, 143, 145, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 162, 166, 168, 173, 178, 183, 184, 187, 189, 190, 192, 193, 194, 195, 197, 198, 199], [28, 58, 63, 67, 73, 100, 129, 137, 138, 146, 159, 161, 174, 181, 182, 196], [94], [8, 120, 167]]


In [217]:
P3=[]
for i in range(len(U3)):
  line = []
  P3.append(line)

In [218]:
for i in range(203):
  for j in U3:
    if S3[i][0]==j:
      P3[U3.tolist().index(j)].append(i)

In [219]:
print(P3)

[[1, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 78, 80, 81, 82, 83, 85, 86, 87, 88, 91, 92, 93, 95, 96, 98, 99, 101, 102, 103, 104, 106, 107, 108, 109, 110, 111, 113, 115, 116, 117, 118, 119, 120, 122, 123, 124, 125, 127, 128, 131, 134, 135, 136, 139, 140, 141, 145, 148, 149, 150, 152, 153, 154, 155, 156, 158, 160, 162, 163, 164, 165, 168, 169, 171, 172, 176, 177, 178, 179, 180, 184, 185, 186, 187, 188, 190, 192, 193, 195, 196, 199, 201], [0, 2, 16, 26, 40, 53, 60, 61, 76, 77, 79, 84, 89, 90, 97, 100, 105, 112, 114, 121, 126, 130, 133, 144, 146, 151, 161, 166, 167, 173, 174, 175, 181, 183, 191, 197, 200, 202], [10, 34, 62, 63, 73, 75, 94, 132, 138, 143, 147, 157, 170, 189, 194], [129, 137, 159, 182, 198], [142]]


In [228]:
import numpy as np
Q1to5 = np.zeros((5,3))

In [227]:
list(range(len(U2),-1,-1))

[5, 4, 3, 2, 1, 0]

In [245]:
print(len(U2))

5


In [229]:
 for i in range(len(R)):
   if i in P2[len(U2)-1]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [230]:
print(Q1to5)

[[1. 2. 0.]
 [0. 2. 1.]
 [0. 3. 0.]
 [1. 2. 0.]
 [0. 3. 0.]]


In [231]:
 for i in range(len(R)):
   if i in P2[len(U2)-2]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [232]:
print(Q1to5)

[[1. 3. 0.]
 [0. 2. 2.]
 [0. 3. 1.]
 [1. 3. 0.]
 [0. 4. 0.]]


In [233]:
 for i in range(len(R)):
   if i in P2[len(U2)-3]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [234]:
 for i in range(len(R)):
   if i in P2[len(U2)-4]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [236]:
print(Q1to5)

[[78.  5. 15.]
 [82.  8.  8.]
 [72. 11. 15.]
 [66. 24.  8.]
 [16. 77.  5.]]


In [249]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))

0.10408163265306122


In [243]:
print(sum(Q1to5[0,:]))

98.0


In [244]:
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))

0.25510204081632654


In [241]:
print(Q1to5[:,1])

[ 5.  8. 11. 24. 77.]


In [224]:
 for i in range(len(R)):
   #for l in range(len(U2),-1,-1):
  if i in P2[len(U2)-1]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1


In [225]:
print(Q1to5)

[[1. 2. 0.]
 [0. 2. 1.]
 [0. 3. 0.]
 [1. 2. 0.]
 [0. 3. 0.]]


In [141]:
for i in range(len(R)):
  for j in range(5):
    for k in Best:
      if eval(R[i])[0][str(j+1)][k] == True:
        Q1to5[j][Best.index(k)] += 1

In [142]:
print(Q1to5)

[[180.   5.  18.]
 [182.   8.  13.]
 [174.  11.  18.]
 [160.  24.  19.]
 [106.  77.  20.]]


In [96]:
print(Q1to5)

[[81.  5. 14.]
 [84.  8.  8.]
 [75. 11. 14.]
 [68. 23.  9.]
 [22. 73.  5.]]


In [77]:
print(Q1to5)

[[81.  5. 14.]
 [84.  8.  8.]
 [75. 11. 14.]
 [69. 23.  8.]
 [22. 73.  5.]]


In [37]:
import numpy as np
Q6 = np.zeros((30,4))

In [38]:
for i in range(len(R)):
  for j in range(6,36):
    for k in Sound:
      if eval(R[i])[0][str(j)][k] == True:
        Q6[j-6][Sound.index(k)] += 1

In [39]:
print(Q6)

[[ 50. 122.  11.  20.]
 [ 91. 101.   3.   8.]
 [ 92. 104.   4.   3.]
 [ 33.   7.   9. 154.]
 [ 39.   9.  11. 144.]
 [ 13.  15.  75. 100.]
 [ 15.  10. 102.  76.]
 [ 17.   9. 150.  27.]
 [ 30. 162.   5.   6.]
 [ 28. 164.   5.   6.]
 [ 28.  35.  65.  75.]
 [ 25.  76.  83.  19.]
 [ 53.   8.  18. 124.]
 [ 70.  29.  45.  59.]
 [ 34.  25.  52.  92.]
 [ 55.  15.  38.  95.]
 [  7.   8.  65. 123.]
 [  4.   7.   3. 189.]
 [ 66.  11.  22. 104.]
 [  7.   8.   1. 187.]
 [ 93. 102.   1.   7.]
 [ 94.  33.  28.  48.]
 [108.  90.   2.   3.]
 [ 14.   7.   5. 177.]
 [  3.   6.   4. 190.]
 [  5.   9.   2. 187.]
 [ 23.   9. 121.  50.]
 [  9.   7. 157.  30.]
 [ 38.  12.  45. 108.]
 [ 42.  22. 108.  31.]]
