<a href="https://colab.research.google.com/github/jjjuurang/CLIP/blob/main/TPAMI631(c).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [250]:
true  = True
false = False

In [251]:
import pandas as pd
csv = pd.read_csv("/content/TPAMI603010.csv",names=["result"])

In [252]:
R = csv['result'].values.tolist()

In [253]:
eval(R[0])[0]["1"]

{'audio': True, 'tedi': False, 'text': False}

In [254]:
eval(R[0])[0]["1"]["audio"]

True

In [255]:
Best = ["audio", "tedi", "text"]
Sound = ["explosion", "fire", "raining", "water"]

In [256]:
import numpy as np
S1 = np.zeros((203,1))
S2 = np.zeros((203,1))
S3 = np.zeros((203,1))

In [257]:
for i in range(len(R)):
  s=0
  for j in range(5):
    if eval(R[i])[0][str(j+1)]["audio"] == True:
      s+=1
  S1[i][0]=s

In [258]:
for i in range(len(R)):
  s=0
  for j in range(5):
    if eval(R[i])[0][str(j+1)]["tedi"] == True:
      s+=1
  S2[i][0]=s

In [259]:
for i in range(len(R)):
  s=0
  for j in range(5):
    if eval(R[i])[0][str(j+1)]["text"] == True:
      s+=1
  S3[i][0]=s

In [260]:
U1=np.unique(S1)
U2=np.unique(S2)
U3=np.unique(S3)

In [261]:
P1=[]
for i in range(len(U1)):
  line = []
  P1.append(line)

In [262]:
for i in range(203):
  for j in U1:
    if S1[i][0]==j:
      P1[U1.tolist().index(j)].append(i)

In [263]:
print(P1)

[[94, 129, 137, 142, 159, 167, 182], [8, 63, 73, 120, 138, 198], [100, 132, 143, 146, 157, 161, 174, 181, 189, 194], [2, 10, 28, 34, 58, 60, 62, 67, 75, 76, 90, 121, 126, 133, 147, 151, 166, 170, 173, 183, 196, 197], [0, 1, 6, 12, 13, 16, 18, 19, 21, 26, 27, 31, 33, 36, 39, 40, 42, 44, 48, 49, 53, 54, 59, 61, 64, 65, 66, 71, 72, 77, 78, 79, 80, 84, 86, 89, 93, 97, 99, 101, 104, 105, 106, 109, 112, 114, 115, 116, 122, 123, 128, 130, 131, 135, 139, 141, 144, 145, 148, 149, 150, 152, 153, 154, 155, 156, 162, 168, 175, 178, 184, 187, 190, 191, 192, 193, 195, 199, 200, 202], [3, 4, 5, 7, 9, 11, 14, 15, 17, 20, 22, 23, 24, 25, 29, 30, 32, 35, 37, 38, 41, 43, 45, 46, 47, 50, 51, 52, 55, 56, 57, 68, 69, 70, 74, 81, 82, 83, 85, 87, 88, 91, 92, 95, 96, 98, 102, 103, 107, 108, 110, 111, 113, 117, 118, 119, 124, 125, 127, 134, 136, 140, 158, 160, 163, 164, 165, 169, 171, 172, 176, 177, 179, 180, 185, 186, 188, 201]]


In [264]:
P2=[]
for i in range(len(U2)):
  line = []
  P2.append(line)

In [265]:
for i in range(203):
  for j in U2:
    if S2[i][0]==j:
      P2[U2.tolist().index(j)].append(i)

In [266]:
print(P2)

[[0, 3, 4, 5, 7, 9, 10, 11, 14, 15, 16, 17, 20, 22, 23, 24, 25, 26, 29, 30, 32, 34, 35, 37, 38, 40, 41, 43, 45, 46, 47, 50, 51, 52, 53, 55, 56, 57, 61, 62, 68, 69, 70, 74, 75, 77, 79, 81, 82, 83, 84, 85, 87, 88, 89, 91, 92, 95, 96, 97, 98, 102, 103, 105, 107, 108, 110, 111, 112, 113, 114, 117, 118, 119, 124, 125, 127, 130, 134, 136, 140, 142, 144, 147, 158, 160, 163, 164, 165, 169, 170, 171, 172, 175, 176, 177, 179, 180, 185, 186, 188, 191, 200, 201, 202], [1, 2, 6, 12, 13, 18, 19, 21, 27, 31, 33, 36, 39, 42, 44, 48, 49, 54, 59, 60, 64, 65, 66, 71, 72, 76, 78, 80, 86, 90, 93, 99, 101, 104, 106, 109, 115, 116, 121, 122, 123, 126, 128, 131, 132, 133, 135, 139, 141, 143, 145, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 162, 166, 168, 173, 178, 183, 184, 187, 189, 190, 192, 193, 194, 195, 197, 198, 199], [28, 58, 63, 67, 73, 100, 129, 137, 138, 146, 159, 161, 174, 181, 182, 196], [94], [8, 120, 167]]


In [267]:
P3=[]
for i in range(len(U3)):
  line = []
  P3.append(line)

In [268]:
for i in range(203):
  for j in U3:
    if S3[i][0]==j:
      P3[U3.tolist().index(j)].append(i)

In [269]:
print(P3)

[[1, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 78, 80, 81, 82, 83, 85, 86, 87, 88, 91, 92, 93, 95, 96, 98, 99, 101, 102, 103, 104, 106, 107, 108, 109, 110, 111, 113, 115, 116, 117, 118, 119, 120, 122, 123, 124, 125, 127, 128, 131, 134, 135, 136, 139, 140, 141, 145, 148, 149, 150, 152, 153, 154, 155, 156, 158, 160, 162, 163, 164, 165, 168, 169, 171, 172, 176, 177, 178, 179, 180, 184, 185, 186, 187, 188, 190, 192, 193, 195, 196, 199, 201], [0, 2, 16, 26, 40, 53, 60, 61, 76, 77, 79, 84, 89, 90, 97, 100, 105, 112, 114, 121, 126, 130, 133, 144, 146, 151, 161, 166, 167, 173, 174, 175, 181, 183, 191, 197, 200, 202], [10, 34, 62, 63, 73, 75, 94, 132, 138, 143, 147, 157, 170, 189, 194], [129, 137, 159, 182, 198], [142]]


In [270]:
import numpy as np
Q1to5 = np.zeros((5,3))

In [271]:
print(len(P2))

5


In [272]:
 for i in range(len(R)):
   if i in P2[4]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [273]:
print(Q1to5)

[[1. 2. 0.]
 [0. 2. 1.]
 [0. 3. 0.]
 [1. 2. 0.]
 [0. 3. 0.]]


In [274]:
 for i in range(len(R)):
   if i in P2[3]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [275]:
print(Q1to5)

[[1. 3. 0.]
 [0. 2. 2.]
 [0. 3. 1.]
 [1. 3. 0.]
 [0. 4. 0.]]


In [276]:
 for i in range(len(R)):
   if i in P2[2]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [277]:
print(Q1to5)

[[ 8.  4.  8.]
 [ 7.  6.  7.]
 [ 3.  9.  8.]
 [ 3. 15.  2.]
 [ 6. 13.  1.]]


In [312]:
Q1to5= np.array([[ 8.,  4.,  8.],
 [ 7.,  6.,  7.],
 [ 3.,  9.,  8.],
 [ 3., 15.,  2.],
 [ 6., 13.,  1.]])

In [358]:
print(Q1to5)

[[ 8.  4.  8.]
 [ 7.  6.  7.]
 [ 3.  9.  8.]
 [ 3. 15.  2.]
 [ 6. 13.  1.]]


In [281]:
n=0

In [354]:
print(len(P2[1]))

78


In [285]:
print(P2[1])

[1, 2, 6, 12, 13, 18, 19, 21, 27, 31, 33, 36, 39, 42, 44, 48, 49, 54, 59, 60, 64, 65, 66, 71, 72, 76, 78, 80, 86, 90, 93, 99, 101, 104, 106, 109, 115, 116, 121, 122, 123, 126, 128, 131, 132, 133, 135, 139, 141, 143, 145, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 162, 166, 168, 173, 178, 183, 184, 187, 189, 190, 192, 193, 194, 195, 197, 198, 199]


In [357]:
print(P2[1][0:3])

[1, 2, 6]


In [356]:
print(P2[1][76:78])

[198, 199]


In [359]:
 for i in range(len(R)):
   if i in P2[1][0:30]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [361]:
print(Q1to5)

[[37.  4.  9.]
 [37.  6.  7.]
 [32. 10.  8.]
 [28. 18.  4.]
 [ 9. 39.  2.]]


In [362]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.12
0.308
0.572


In [364]:
 for i in range(len(R)):
   if i in P2[1][0:28]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [365]:
for i in range(len(R)):
  if i in P1[5][0:2]:
    for j in range(5):
      for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [367]:
print(Q1to5)

[[37.  4.  9.]
 [37.  6.  7.]
 [32. 10.  8.]
 [29. 18.  3.]
 [11. 37.  2.]]


In [366]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.116
0.3
0.584


In [363]:
Q1to5= np.array([[ 8.,  4.,  8.],
 [ 7.,  6.,  7.],
 [ 3.,  9.,  8.],
 [ 3., 15.,  2.],
 [ 6., 13.,  1.]])

In [ ]:
for i in range(len(R)):
  if i in P1[5][0:2]:
    for j in range(5):
      for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [ ]:
 for i in range(len(R)):
   if i in P2[1][0:30]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [342]:
Q1to5= np.array([[ 8.,  4.,  8.],
 [ 7.,  6.,  7.],
 [ 3.,  9.,  8.],
 [ 3., 15.,  2.],
 [ 6., 13.,  1.]])

In [344]:
print(Q1to5)

[[37.  4.  9.]
 [37.  6.  7.]
 [32. 10.  8.]
 [28. 18.  4.]
 [ 9. 39.  2.]]


In [345]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.12
0.308
0.572


In [350]:
Q1to5= np.array([[ 8.,  4.,  8.],
 [ 7.,  6.,  7.],
 [ 3.,  9.,  8.],
 [ 3., 15.,  2.],
 [ 6., 13.,  1.]])

In [347]:
for i in range(len(R)):
  if i in P2[1][3:33]:
    for j in range(5):
      for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [349]:
print(Q1to5)

[[37.  4.  9.]
 [37.  6.  7.]
 [32. 10.  8.]
 [29. 18.  3.]
 [ 9. 39.  2.]]


In [348]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.116
0.308
0.576


In [ ]:
for i in range(len(R)):
  if i in P2[1][3:33]:
    for j in range(5):
      for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [351]:
print(Q1to5)

[[ 8.  4.  8.]
 [ 7.  6.  7.]
 [ 3.  9.  8.]
 [ 3. 15.  2.]
 [ 6. 13.  1.]]


In [332]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.11153846153846154
0.29615384615384616
0.5923076923076923


In [335]:
print(sum(Q1to5[:,1])

SyntaxError: ignored

In [338]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[:,1])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.11153846153846154
0.2
0.5923076923076923


In [329]:
for i in range(len(R)):
  if i in P1[5][0:2]:
    for j in range(5):
      for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [289]:
print(Q1to5)

[[37.  4.  9.]
 [37.  6.  7.]
 [32. 10.  8.]
 [28. 18.  4.]
 [ 9. 39.  2.]]


In [ ]:
for i in range(len(R)):
  if i in P1[5][0:2]:
    for j in range(5):
      for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [309]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.168
0.308
0.524


In [301]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.116
0.3
0.584


In [378]:
import numpy as np
Q6 = np.zeros((30,4))

In [379]:
for i in range(len(R)):
  if i in P1[5][0:2]:
    for j in range(6,36):
      for k in Sound:
        if eval(R[i])[0][str(j)][k] == True:
          Q6[j-6][Sound.index(k)] += 1

In [380]:
for i in range(len(R)):
  if i in P2[1][0:28]:
    for j in range(6,36):
      for k in Sound:
        if eval(R[i])[0][str(j)][k] == True:
          Q6[j-6][Sound.index(k)] += 1

In [386]:
for i in range(len(R)):
  if i in P2[4]:
    for j in range(6,36):
      for k in Sound:
        if eval(R[i])[0][str(j)][k] == True:
          Q6[j-6][Sound.index(k)] += 1

In [387]:
print(Q6)

[[14. 26.  2.  8.]
 [19. 28.  2.  1.]
 [19. 31.  0.  0.]
 [ 4.  0.  5. 41.]
 [13.  2.  6. 29.]
 [ 3.  2. 19. 26.]
 [ 4.  1. 23. 22.]
 [ 4.  2. 34. 10.]
 [ 7. 38.  2.  3.]
 [11. 35.  3.  1.]
 [11.  5. 18. 16.]
 [ 7. 16. 23.  4.]
 [14.  0.  4. 32.]
 [16.  9. 13. 12.]
 [10.  4. 16. 20.]
 [12.  3. 10. 25.]
 [ 4.  3. 15. 28.]
 [ 1.  2.  2. 45.]
 [12.  4.  8. 26.]
 [ 3.  3.  1. 43.]
 [19. 28.  0.  3.]
 [18.  8.  7. 17.]
 [24. 24.  1.  1.]
 [ 1.  2.  4. 43.]
 [ 1.  1.  2. 46.]
 [ 2.  2.  1. 45.]
 [ 7.  2. 28. 13.]
 [ 3.  2. 39.  6.]
 [10.  3. 13. 24.]
 [10. 11. 24.  5.]]


In [392]:
Q6[6:8,2]

array([23., 34.])

In [393]:
sum(Q6[0:3,0])+ sum(Q6[3:6,3]) +sum(Q6[6:8,2])+ sum(Q6[8:10,1])

278.0

In [394]:
278/(50*10)

0.556

In [395]:
sum(Q6[10:13,0])+ sum(Q6[13:16,3]) +sum(Q6[16:18,2])+ sum(Q6[18:20,1])

113.0

In [396]:
113/(50*10)

0.226

In [397]:
sum(Q6[20:23,0])+ sum(Q6[23:26,3]) +sum(Q6[26:28,2])+ sum(Q6[28:30,1])

276.0

In [398]:
276/500

0.552

In [399]:
19+18+24+11+3+39+28+45+46+43

276

In [388]:
(19+18+24+11+3+39+28+45+46+43)/(50*10)

55.199999999999996

In [290]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))

0.12


In [291]:
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))

0.308


In [292]:
print(sum(Q1to5[:,0])/(sum(Q1to5[0,:])*5))

0.572


In [ ]:
for i in range(len(R)):
  if i in P2[1][0:30]:
    for j in range(5):
      for k in Best:
      if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [279]:

for i in range(len(R)):
  if i in P2[1][0:30]:
    for j in range(5):
      for k in Best:
      if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1

In [280]:
print(Q1to5)

[[78.  5. 15.]
 [82.  8.  8.]
 [72. 11. 15.]
 [66. 24.  8.]
 [16. 77.  5.]]


In [236]:
print(Q1to5)

[[78.  5. 15.]
 [82.  8.  8.]
 [72. 11. 15.]
 [66. 24.  8.]
 [16. 77.  5.]]


In [249]:
print(sum(Q1to5[:,2])/(sum(Q1to5[0,:])*5))

0.10408163265306122


In [243]:
print(sum(Q1to5[0,:]))

98.0


In [244]:
print(sum(Q1to5[:,1])/(sum(Q1to5[0,:])*5))

0.25510204081632654


In [241]:
print(Q1to5[:,1])

[ 5.  8. 11. 24. 77.]


In [224]:
 for i in range(len(R)):
   #for l in range(len(U2),-1,-1):
  if i in P2[len(U2)-1]:
    for j in range(5):
       for k in Best:
        if eval(R[i])[0][str(j+1)][k] == True:
          Q1to5[j][Best.index(k)] += 1


In [225]:
print(Q1to5)

[[1. 2. 0.]
 [0. 2. 1.]
 [0. 3. 0.]
 [1. 2. 0.]
 [0. 3. 0.]]


In [141]:
for i in range(len(R)):
  for j in range(5):
    for k in Best:
      if eval(R[i])[0][str(j+1)][k] == True:
        Q1to5[j][Best.index(k)] += 1

In [142]:
print(Q1to5)

[[180.   5.  18.]
 [182.   8.  13.]
 [174.  11.  18.]
 [160.  24.  19.]
 [106.  77.  20.]]


In [96]:
print(Q1to5)

[[81.  5. 14.]
 [84.  8.  8.]
 [75. 11. 14.]
 [68. 23.  9.]
 [22. 73.  5.]]


In [77]:
print(Q1to5)

[[81.  5. 14.]
 [84.  8.  8.]
 [75. 11. 14.]
 [69. 23.  8.]
 [22. 73.  5.]]


In [368]:
import numpy as np
Q6 = np.zeros((30,4))

In [ ]:
for i in range(len(R)):
  for j in range(6,36):
    for k in Sound:
      if eval(R[i])[0][str(j)][k] == True:
        Q6[j-6][Sound.index(k)] += 1

In [38]:
for i in range(len(R)):
  for j in range(6,36):
    for k in Sound:
      if eval(R[i])[0][str(j)][k] == True:
        Q6[j-6][Sound.index(k)] += 1

In [39]:
print(Q6)

[[ 50. 122.  11.  20.]
 [ 91. 101.   3.   8.]
 [ 92. 104.   4.   3.]
 [ 33.   7.   9. 154.]
 [ 39.   9.  11. 144.]
 [ 13.  15.  75. 100.]
 [ 15.  10. 102.  76.]
 [ 17.   9. 150.  27.]
 [ 30. 162.   5.   6.]
 [ 28. 164.   5.   6.]
 [ 28.  35.  65.  75.]
 [ 25.  76.  83.  19.]
 [ 53.   8.  18. 124.]
 [ 70.  29.  45.  59.]
 [ 34.  25.  52.  92.]
 [ 55.  15.  38.  95.]
 [  7.   8.  65. 123.]
 [  4.   7.   3. 189.]
 [ 66.  11.  22. 104.]
 [  7.   8.   1. 187.]
 [ 93. 102.   1.   7.]
 [ 94.  33.  28.  48.]
 [108.  90.   2.   3.]
 [ 14.   7.   5. 177.]
 [  3.   6.   4. 190.]
 [  5.   9.   2. 187.]
 [ 23.   9. 121.  50.]
 [  9.   7. 157.  30.]
 [ 38.  12.  45. 108.]
 [ 42.  22. 108.  31.]]
